/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project487w.rohanmankame;

import com.sun.jdi.connect.spi.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Rohan_nu3d8wo
 */
public class DataBaseGUI extends javax.swing.JFrame {

    /**
     * Creates new form DataBaseGUI
     */
    public DataBaseGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        SUNlabAccessButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        AccessTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SUNlabAccessButton.setText("Show SunLAB access Data");
        SUNlabAccessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUNlabAccessButtonActionPerformed(evt);
            }
        });

        AccessTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date of Entry"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(AccessTable);

        jLabel1.setText("Search by Student ID: ");

        jLabel2.setText("Show all SunLAB access: ");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setText("Seacrh by ID");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Search by Date: ");

        jButton3.setText("Search by Date");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Search by Time range: ");

        jButton4.setText("Search by Time");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel5.setText("End Time:");

        jLabel6.setText("Start time:");

        jButton5.setText("Search by ID, Date & Time range");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setText("Enter in YYYY/MM/DD format");

        jLabel8.setText("Enter in Hour:Min:Sec format");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SUNlabAccessButton))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(96, 96, 96))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButton2)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jButton3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel7)))
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jButton1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(SUNlabAccessButton))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jLabel7))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jLabel8))
                        .addGap(43, 43, 43)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AdminPortalGUI AdminGUI = new AdminPortalGUI();
        AdminGUI.show();
        dispose(); //close current frame
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SUNlabAccessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUNlabAccessButtonActionPerformed
       
        ((DefaultTableModel)AccessTable.getModel()).setNumRows(0);
        try {
            java.sql.Connection con = null;
            String username = "root";
            String password= "rohan";
            String dataConn = "jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=CONVERT_TO_NULL";//"jdbc:mysql://localhost:3306/sunlabswipe";
            Statement stmt = null;
            
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(dataConn,username,password);
            System.out.print("sql connection works");
            String sql = "SELECT * FROM sunlabswipe.labaccess";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)AccessTable.getModel();
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1),rs.getString(2)});
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SQLupdateStatus.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SQLupdateStatus.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_SUNlabAccessButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        //jScrollPane2.rev
        
        
        ((DefaultTableModel)AccessTable.getModel()).setNumRows(0);
        
        
        
                try {
            java.sql.Connection con = null;
            String username = "root";
            String password= "rohan";
            String dataConn = "jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=CONVERT_TO_NULL";//"jdbc:mysql://localhost:3306/sunlabswipe";
            Statement stmt = null;
            
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(dataConn,username,password);
            System.out.print("sql connection works");
            String ID = jTextField1.getText();
            String sql = "SELECT * FROM sunlabswipe.labaccess WHERE ID = "+ ID +";";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)AccessTable.getModel();
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1),rs.getString(2)});
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SQLupdateStatus.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SQLupdateStatus.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                ((DefaultTableModel)AccessTable.getModel()).setNumRows(0);
        
        
        
                try {
            java.sql.Connection con = null;
            String username = "root";
            String password= "rohan";
            String dataConn = "jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=CONVERT_TO_NULL";//"jdbc:mysql://localhost:3306/sunlabswipe";
            Statement stmt = null;
            
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(dataConn,username,password);
            System.out.print("sql connection works");
            String SearchDate = jTextField2.getText();
            String sql = "SELECT * FROM sunlabswipe.labaccess;";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)AccessTable.getModel();
            String[] TempDate;
            String Date;
            while(rs.next()){
                
                TempDate = rs.getString(2).split(" ");
                System.out.println("in here");
                System.out.println(Arrays.toString(TempDate));
                //Date1 = TempDateSplit.split(",");
                System.out.println(String.valueOf(TempDate[0]) );
                Date = String.valueOf(TempDate[0]);
                
                if(Date.equals(SearchDate)){
                    
                    model.addRow(new String[]{rs.getString(1),rs.getString(2)});
                    
                }else{
                    
                }
                
                //model.addRow(new String[]{rs.getString(1),rs.getString(2)});
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SQLupdateStatus.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SQLupdateStatus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        
                ((DefaultTableModel)AccessTable.getModel()).setNumRows(0);
        
        
        
                try {
            java.sql.Connection con = null;
            String username = "root";
            String password= "rohan";
            String dataConn = "jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=CONVERT_TO_NULL";//"jdbc:mysql://localhost:3306/sunlabswipe";
            Statement stmt = null;
            
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(dataConn,username,password);
            System.out.print("sql connection works");
            String[] TimeStart;
            String[] TimeEnd;
            String SearchDateStart = jTextField3.getText();
            String SearchDateEnd = jTextField4.getText();
            TimeStart = SearchDateStart.split(":");
            TimeEnd = SearchDateEnd.split(":");
            int TS1 =  Integer.valueOf(TimeStart[0]);
            int TS2 =  Integer.valueOf(TimeStart[1]);
            //int TS3 =  Integer.valueOf(TimeStart[3]);
            int TE1 =  Integer.valueOf(TimeEnd[0]);
            int TE2 =  Integer.valueOf(TimeEnd[1]);
            //int TE3 =  Integer.valueOf(TimeEnd[3]);
            String sql = "SELECT * FROM sunlabswipe.labaccess;";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)AccessTable.getModel();
            
            String[] timeStamp;
            String Time;
            int Time1;
            int Time2;
            //int Time3;
            String[] TimeSplitArr;
            while(rs.next()){
                
                timeStamp = rs.getString(2).split(" ");
                System.out.println("in here");
                System.out.println(Arrays.toString(timeStamp));
                //Date1 = TempDateSplit.split(",");
                System.out.println(String.valueOf(timeStamp[1]) );
                Time = String.valueOf(timeStamp[1]);
                TimeSplitArr = Time.split(":");
                Time1 = Integer.valueOf(TimeSplitArr[0]);
                //Time2 = Integer.valueOf(TimeSplitArr[1]);
                System.out.println(Time1);
                //System.out.println(Time2);
                //Time3 = Integer.valueOf(TimeSplitArr[2]);
                
                if((Time1 >TS1 && Time1 < TE1)){
                    
                    model.addRow(new String[]{rs.getString(1),rs.getString(2)});
                    
                }else{
                    
                }
                
                //model.addRow(new String[]{rs.getString(1),rs.getString(2)});
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SQLupdateStatus.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SQLupdateStatus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
                
                ((DefaultTableModel)AccessTable.getModel()).setNumRows(0);
                try {
            java.sql.Connection con = null;
            String username = "root";
            String password= "rohan";
            String dataConn = "jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=CONVERT_TO_NULL";//"jdbc:mysql://localhost:3306/sunlabswipe";
            Statement stmt = null;
            
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(dataConn,username,password);
            System.out.print("sql connection works");
            String[] TimeStart;
            String[] TimeEnd;
            String SearchDateStart = jTextField3.getText();
            String SearchDateEnd = jTextField4.getText();
            TimeStart = SearchDateStart.split(":");
            TimeEnd = SearchDateEnd.split(":");
            int TS1 =  Integer.valueOf(TimeStart[0]);
            int TS2 =  Integer.valueOf(TimeStart[1]);
            //int TS3 =  Integer.valueOf(TimeStart[3]);
            int TE1 =  Integer.valueOf(TimeEnd[0]);
            int TE2 =  Integer.valueOf(TimeEnd[1]);
            //int TE3 =  Integer.valueOf(TimeEnd[3]);
            String ID = jTextField1.getText();
            String SearchDate = jTextField2.getText();
            
            String sql = "SELECT * FROM sunlabswipe.labaccess WHERE ID = "+ ID +";";
            //String sql = "SELECT * FROM sunlabswipe.labaccess;";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)AccessTable.getModel();
            
            String[] timeStamp;
            String Date;
            String Time;
            int Time1;
            int Time2;
            //int Time3;
            String[] TimeSplitArr;
            while(rs.next()){
                
                timeStamp = rs.getString(2).split(" ");
                System.out.println("in here");
                System.out.println(Arrays.toString(timeStamp));
                //Date1 = TempDateSplit.split(",");
                System.out.println(String.valueOf(timeStamp[1]) );
                Date = String.valueOf(timeStamp[0]);
                /////////////////////////////////////////////////////////////
                Time = String.valueOf(timeStamp[1]);
                TimeSplitArr = Time.split(":");
                Time1 = Integer.valueOf(TimeSplitArr[0]);
                //Time2 = Integer.valueOf(TimeSplitArr[1]);
                System.out.println(Time1);
                //System.out.println(Time2);
                //Time3 = Integer.valueOf(TimeSplitArr[2]);
                
                if((Time1 >TS1 && Time1 < TE1) && (SearchDate.equals(Date))){
                    
                    model.addRow(new String[]{rs.getString(1),rs.getString(2)});
                    
                }else{
                    
                }
                
                //model.addRow(new String[]{rs.getString(1),rs.getString(2)});
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SQLupdateStatus.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SQLupdateStatus.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataBaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataBaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataBaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataBaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataBaseGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AccessTable;
    private javax.swing.JButton SUNlabAccessButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
