/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project487w.rohanmankame;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rohan_nu3d8wo
 */
public class IDStatusGUI extends javax.swing.JFrame {

    /**
     * Creates new form IDStatusGUI
     */
    public IDStatusGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ActivateIDtext = new javax.swing.JTextField();
        DeactivateIDtext = new javax.swing.JTextField();
        ReactivateIDtext = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        roleActivatetext = new javax.swing.JTextField();
        roleDeactivatetext = new javax.swing.JTextField();
        roleReactivatetext = new javax.swing.JTextField();
        ActivateButton = new javax.swing.JButton();
        DeactivateID = new javax.swing.JButton();
        ReactivateID = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Activate ID");

        jLabel2.setText("Deactivate ID");

        jLabel3.setText("Reactivate ID");

        ActivateIDtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActivateIDtextActionPerformed(evt);
            }
        });

        jLabel4.setText("Role:");

        jLabel5.setText("Role:");

        jLabel6.setText("Role:");

        ActivateButton.setText("Activate ID");
        ActivateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActivateButtonActionPerformed(evt);
            }
        });

        DeactivateID.setText("DeActivate ID");
        DeactivateID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeactivateIDActionPerformed(evt);
            }
        });

        ReactivateID.setText("Reactivate ID");
        ReactivateID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReactivateIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ActivateIDtext)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReactivateIDtext))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roleActivatetext))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roleReactivatetext)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeactivateIDtext))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roleDeactivatetext)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(419, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ActivateButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DeactivateID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ReactivateID, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ActivateIDtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(roleActivatetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ActivateButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(DeactivateIDtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(roleDeactivatetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeactivateID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ReactivateIDtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(roleReactivatetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ReactivateID)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AdminPortalGUI AdminGUI = new AdminPortalGUI();
        AdminGUI.show();
        dispose(); //close current frame
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ActivateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActivateButtonActionPerformed
        // TODO add your handling code here:
        
            java.sql.Connection con = null;
            String username = "root";
            String password= "rohan";
            String dataConn = "jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=CONVERT_TO_NULL";//"jdbc:mysql://localhost:3306/sunlabswipe";
            Statement stmt = null;
            
        try {
            //Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(dataConn,username,password);
        } catch (SQLException ex) {
            Logger.getLogger(IDStatusGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        int ID = Integer.valueOf(ActivateIDtext.getText());
        String STATUS = "Active";
        String ROLE = roleActivatetext.getText();
            System.out.print("sql connection works");
            String sql = "INSERT INTO sunlabswipe.userstatus VALUES("+ ID +", '"+STATUS+"' ,"+"'"+ROLE+"');";
            //INSERT INTO sunlabswipe.userstatus VALUES(578462,"active","student");
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(IDStatusGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_ActivateButtonActionPerformed

    private void ActivateIDtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActivateIDtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActivateIDtextActionPerformed

    private void DeactivateIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeactivateIDActionPerformed
        // TODO add your handling code here:
                 java.sql.Connection con = null;
            String username = "root";
            String password= "rohan";
            String dataConn = "jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=CONVERT_TO_NULL";//"jdbc:mysql://localhost:3306/sunlabswipe";
            Statement stmt = null;
            
        try {
            //Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(dataConn,username,password);
        } catch (SQLException ex) {
            Logger.getLogger(IDStatusGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        int ID = Integer.valueOf(DeactivateIDtext.getText());
        String STATUS = "Active";
        String ROLE = roleDeactivatetext.getText();
            System.out.print("sql connection works");
            String sql = "UPDATE sunlabswipe.userstatus SET Status = \"Deactivated\" WHERE ID = "+ID +";";
            //UPDATE sunlabswipe.userstatus SET Status = "Deactivated" WHERE ID = 578462;
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(IDStatusGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeactivateIDActionPerformed

    private void ReactivateIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReactivateIDActionPerformed
        // TODO add your handling code here:
        
                  java.sql.Connection con = null;
            String username = "root";
            String password= "rohan";
            String dataConn = "jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=CONVERT_TO_NULL";//"jdbc:mysql://localhost:3306/sunlabswipe";
            Statement stmt = null;
            
        try {
            //Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(dataConn,username,password);
        } catch (SQLException ex) {
            Logger.getLogger(IDStatusGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        int ID = Integer.valueOf(ReactivateIDtext.getText());
        String STATUS = "Active";
        String ROLE = roleDeactivatetext.getText();
            System.out.print("sql connection works");
            String sql = "UPDATE sunlabswipe.userstatus SET Status = \"Active\" WHERE ID = "+ID +";";
            //UPDATE sunlabswipe.userstatus SET Status = "Deactivated" WHERE ID = 578462;
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(IDStatusGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ReactivateIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IDStatusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IDStatusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IDStatusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IDStatusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IDStatusGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActivateButton;
    private javax.swing.JTextField ActivateIDtext;
    private javax.swing.JButton DeactivateID;
    private javax.swing.JTextField DeactivateIDtext;
    private javax.swing.JButton ReactivateID;
    private javax.swing.JTextField ReactivateIDtext;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField roleActivatetext;
    private javax.swing.JTextField roleDeactivatetext;
    private javax.swing.JTextField roleReactivatetext;
    // End of variables declaration//GEN-END:variables
}
