/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project487w.rohanmankame;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.*;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rohan_nu3d8wo
 */
public class ScannerGUI extends javax.swing.JFrame {

    /**
     * Creates new form ScannerGUI
     */
    public ScannerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PSUIDl = new javax.swing.JLabel();
        PSUIDinput = new javax.swing.JTextField();
        SwipeIDbutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PSUIDl.setText("PSU ID:");

        PSUIDinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSUIDinputActionPerformed(evt);
            }
        });

        SwipeIDbutton.setText("Swipe ID to enter SunLAB");
        SwipeIDbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwipeIDbuttonActionPerformed(evt);
            }
        });

        jButton1.setText("Enter Admin Portal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Swipe PSU ID to enter the SUN LAB!!!");
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("Swipe ID to exit SunLab");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PSUIDl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SwipeIDbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(PSUIDinput))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PSUIDl)
                    .addComponent(PSUIDinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SwipeIDbutton)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PSUIDinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSUIDinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PSUIDinputActionPerformed

    private void SwipeIDbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwipeIDbuttonActionPerformed
        // TODO add your handling code here:
        String PSUID = PSUIDinput.getText();
        System.out.println(PSUID);
        
        //MUST CHECK IF ID IS VALID
        jTextArea1.setText("Welcome to the SUN LAB");
        
        try{
            
            java.sql.Connection con = null;
            String username = "root";
            String password= "rohan";
            String dataConn = "jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=CONVERT_TO_NULL";//"jdbc:mysql://localhost:3306/sunlabswipe";
            Statement stmt = null;
            ResultSet results =null;
            int IDfound;
            con = DriverManager.getConnection(dataConn,username,password);
            stmt = con.createStatement();
            int ID = Integer.valueOf(PSUIDinput.getText());
            String sql = "SELECT * FROM sunlabswipe.userstatus WHERE ID = "+"'"+ ID+"' AND Status = \"Active\";";
            //SELECT * FROM sunlabswipe.userstatus WHERE ID = 683826 AND Status = "Active";
            
            ResultSet rs = stmt.executeQuery(sql);
            if(rs.next()){
                System.out.println("ID found");
                IDfound = 1;
                
            }else{
                System.out.println("ID not found");
                IDfound = 0;
            }
            
            
        if(IDfound == 0){
            
            jTextArea1.setText("YOU DO NOT HAVE PERMISION TO ENTER THE SUNLAB!!!! (Contact a staff member to activate your ID)");
            
        }else{//WHEN ID IS FOUND IN DB AND USER STATUS IS ACTIVE
            //String Date;
            
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
            LocalDateTime DateTime = LocalDateTime.now();
            String StrDateTime = String.valueOf(dtf.format(DateTime));
            System.out.println(DateTime);
            System.out.println(StrDateTime);
            
            
            sql = "INSERT INTO sunlabswipe.labaccess VALUES("+ ID +",'"+StrDateTime+"');";
            //INSERT INTO sunlabswipe.userstatus VALUES(578462,"active","student");
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(IDStatusGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
            
            
            
            
        }catch(Exception e){
            System.out.println("error accessing DB");
        }
        
        
        

        
         
    }//GEN-LAST:event_SwipeIDbuttonActionPerformed
    

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        AdminLoginGUI AdminPortallogin = new AdminLoginGUI();
        AdminPortallogin.show();
        dispose(); //close current frame
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
                String PSUID = PSUIDinput.getText();
        System.out.println(PSUID);
        
        //MUST CHECK IF ID IS VALID
        //jTextArea1.setText("Welcome to the SUN LAB");
        
        try{
            
            java.sql.Connection con = null;
            String username = "root";
            String password= "rohan";
            String dataConn = "jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=CONVERT_TO_NULL";//"jdbc:mysql://localhost:3306/sunlabswipe";
            Statement stmt = null;
            ResultSet results =null;
            int IDfound;
            con = DriverManager.getConnection(dataConn,username,password);
            stmt = con.createStatement();
            int ID = Integer.valueOf(PSUIDinput.getText());
            String sql = "SELECT * FROM sunlabswipe.userstatus WHERE ID = "+"'"+ ID+"' AND Status = \"Active\";";
            //SELECT * FROM sunlabswipe.userstatus WHERE ID = 683826 AND Status = "Active";
            
            ResultSet rs = stmt.executeQuery(sql);
            if(rs.next()){
                System.out.println("ID found");
                IDfound = 1;
                
            }else{
                System.out.println("ID not found");
                IDfound = 0;
            }
            
            
        if(IDfound == 0){
            
            jTextArea1.setText("YOU ARE NOT EVEN ALLOWED IN HERE!!!! (You will be arrested)");
            
        }else{//WHEN ID IS FOUND IN DB AND USER STATUS IS ACTIVE
            //String Date;
            jTextArea1.setText("BYE BYE! HAVE A NICE DAY!");
            
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
            LocalDateTime DateTime = LocalDateTime.now();
            String StrDateTime = String.valueOf(dtf.format(DateTime));
            System.out.println(DateTime);
            System.out.println(StrDateTime);
            
            
            sql = "INSERT INTO sunlabswipe.labaccess VALUES("+ ID +",'"+StrDateTime+"');";
            //INSERT INTO sunlabswipe.userstatus VALUES(578462,"active","student");
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(IDStatusGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
            
            
            
            
        }catch(Exception e){
            System.out.println("error accessing DB");
        }
        
        
        

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScannerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScannerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScannerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScannerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScannerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PSUIDinput;
    private javax.swing.JLabel PSUIDl;
    private javax.swing.JButton SwipeIDbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
